### ISSUE TITLE
Multiple desktops and screens

### ISSUE THREAD

**Issue by steveoh** [Habbie/mjomatic#2]
how do you deal with multiple desktops and screens with this?

**Comment by Habbie** [comment]
I have not put any effort into making that work yet, sorry

**Comment by steveoh** [comment]
It would be great to have `go` take a screen number. Is that something you could give me a little direction on and I could send a pull request? Would it just be [this](https://github.com/Habbie/mjomatic/blob/master/mjomatic.lua#L144)

**Comment by Habbie** [comment]
If I had to guess, it's more about lines 25-26.
